<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2570db3dfba7d0d338c2c44087483f42
{
    public static $files = [
        '7b11c4dc42b3b3023073cb14e519683c' => __DIR__ . '/..' . '/ralouphie/getallheaders/src/getallheaders.php',
    ];

    public static $prefixLengthsPsr4 = [
        'P' => [
             'Psr\\Http\\Message\\' => 17,
         ],
        'I' => [
             'Intervention\\Image\\' => 19,
         ],
        'G' => [
             'GuzzleHttp\\Psr7\\' => 16,
         ],
    ];

    public static $prefixDirsPsr4 = [
        'Psr\\Http\\Message\\' => [
             0 => __DIR__ . '/..' . '/psr/http-message/src',
             1 => __DIR__ . '/..' . '/psr/http-factory/src',
         ],
        'Intervention\\Image\\' => [
             0 => __DIR__ . '/..' . '/intervention/image/src/Intervention/Image',
         ],
        'GuzzleHttp\\Psr7\\' => [
             0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
         ],
    ];

    public static $classMap = [
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    ];

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader): void {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2570db3dfba7d0d338c2c44087483f42::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2570db3dfba7d0d338c2c44087483f42::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit2570db3dfba7d0d338c2c44087483f42::$classMap;
        }, null, ClassLoader::class);
    }
}
