<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return [
    'Psr\\Http\\Message\\' => [$vendorDir . '/psr/http-message/src', $vendorDir . '/psr/http-factory/src'],
    'Intervention\\Image\\' => [$vendorDir . '/intervention/image/src/Intervention/Image'],
    'GuzzleHttp\\Psr7\\' => [$vendorDir . '/guzzlehttp/psr7/src'],
];
