<?php return [
    'root' => [
        'name' => 'imangalis/init_wp',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '1a72709f2d5176ddbc593051a94326844a0f8970',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => [],
        'dev' => true,
    ],
    'versions' => [
        'guzzlehttp/psr7' => [
            'pretty_version' => '2.6.1',
            'version' => '2.6.1.0',
            'reference' => 'be45764272e8873c72dbe3d2edcfdfcc3bc9f727',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'imangalis/init_wp' => [
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '1a72709f2d5176ddbc593051a94326844a0f8970',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'intervention/image' => [
            'pretty_version' => '2.7.2',
            'version' => '2.7.2.0',
            'reference' => '04be355f8d6734c826045d02a1079ad658322dad',
            'type' => 'library',
            'install_path' => __DIR__ . '/../intervention/image',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'psr/http-factory' => [
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'e616d01114759c4c489f93b099585439f795fe35',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'psr/http-factory-implementation' => [
            'dev_requirement' => false,
            'provided' => [
                0 => '1.0',
            ],
        ],
        'psr/http-message' => [
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'psr/http-message-implementation' => [
            'dev_requirement' => false,
            'provided' => [
                0 => '1.0',
            ],
        ],
        'ralouphie/getallheaders' => [
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => [],
            'dev_requirement' => false,
        ],
    ],
];
